extends Node
## Lang.gd (Autoload) —— V1.3 双语文案（默认中文，可切换英文，持久化）。
## 用法：Lang.t("key") / Lang.f("key", [args])；语言切换会 emit language_changed。
## 所有 UI 文案统一 key，不在脚本内散落硬编码。

const FILE_PATH := "user://lang.json"

signal language_changed(lang_code: String)

var lang: String = "zh"
var lang_zh := false

const _ZH := {
	"game_title": "地牢主脑：过载危机",
	"game_title_en": "CORE OVERLOAD",
	"version_tag": "V1.3",
	"tutorial_t1": "WASD 移动 · 鼠标瞄准 · 左键射击 · Q 换武器",
	"tutorial_t2": "Shift / 空格：翻滚闪避（无敌帧可穿弹）",
	"tutorial_t3": "按住 V：主动泄压（期间无法射击，是管理过载的关键）",
	"tutorial_t4": "F：治疗瓶 · R：系统技能（由构筑决定）· Tab：构筑 · ESC：暂停",
	"tutorial_t5": "清空房间后进入路线图挑选下一个节点；安全状态下会自动断点存档",
	"lang_switch_hint": "按 L 切换语言",

	# ---------------- 新手教学关卡 ----------------
	"room_tutorial": "教学模拟",
	"reward_tutorial": "掌握全部操作",
	"tutorial_title": "操作训练",
	"tutorial_hud_tag": "训练模式",
	"tutorial_step_label": "训练 %d / %d",
	"tutorial_goal_move": "用 W A S D 移动到发光标记处",
	"tutorial_goal_shoot": "移动鼠标瞄准训练假人，按住左键射击 · 命中 3 次",
	"tutorial_goal_roll": "按 Shift 或空格翻滚闪避 · 翻滚有无敌帧",
	"tutorial_goal_swap": "按 Q 切换武器（教学补给已发放副武器）",
	"tutorial_goal_vent": "按住 V 主动泄压，把过载条压到 5% 以下（泄压时无法射击）",
	"tutorial_goal_skill": "按 R 释放系统技能 · 技能由你的构筑决定",
	"tutorial_done": "训练完成 · 走上右侧传送门继续",
	"tutorial_dummy": "训练假人",
	"tutorial_move_marker": "走到这里",
	"tutorial_swap_bonus": "教学补给：获得副武器",
	"tutorial_hint_safe": "训练场不会受伤 · 按 ESC 可暂停并放弃",
	"menu_tutorial": "训练关卡",
	"menu_tutorial_sub": "重玩操作教学 · 不影响当前存档",

	# ---------------- HUD ----------------
	"hud_hp": "HP",
	"hud_gold": "金币",
	"hud_cells": "细胞",
	"hud_energy": "能量",
	"hud_source": "源代码",
	"hud_kills": "击杀",
	"hud_score": "得分",
	"hud_room": "房间",
	"hud_flask": "治疗瓶",
	"hud_fire": "火力",
	"hud_cool": "散热",
	"hud_struct": "结构",
	"hud_weapon": "武器",
	"hud_empty": "空",
	"hud_roll": "翻滚",
	"hud_overload": "过载",
	"hud_build": "构筑",
	"hud_chain": "连锁",
	"hud_depth": "深度",
	"hud_rules": "异常",
	"hud_no_rule": "无异常",
	"hud_tags": "标签",
	"hud_cards": "过载卡",
	"hud_scrolls": "卷轴",

	# ---------------- 过载 ----------------
	"overload_stable": "稳定",
	"overload_high": "高负载",
	"overload_danger": "危险",
	"overload_critical": "临界",
	"overload_meltdown": "崩溃",
	"overload_vent_hint": "按住 V 泄压",
	"overload_vented": "泄压中",
	"melt_blackout": "设备断电 —— 全场停机",
	"melt_surge": "电涌 —— 故障体入侵",
	"melt_burn": "核心灼伤 —— 损失生命",
	"melt_emp": "EMP 脉冲 —— 过载归零，资源返还",

	# ---------------- 区块 / 房间 ----------------
	"biome_1": "冷却水道",
	"biome_2": "服务器墓场",
	"biome_3": "主脑核心",
	"room_combat": "战斗房",
	"room_elite": "精英房",
	"room_treasure": "宝藏房",
	"room_repair": "维修房",
	"room_shop": "黑市",
	"room_lab": "实验室",
	"room_glitch": "故障房",
	"room_harvest": "收割房",
	"room_hack": "底层骇入",
	"room_boss": "BOSS 房",
	"room_clear": "房间已清空",
	"room_locked": "警告：房门已锁定",
	"room_next": "前往路线图选择下一节点",

	"reward_combat": "金币 / 细胞",
	"reward_elite": "高品质卷轴 / 协议",
	"reward_treasure": "宝箱 / 卷轴",
	"reward_repair": "回复 HP / 清除过载",
	"reward_shop": "金币交易",
	"reward_lab": "临时改造",
	"reward_glitch": "能量碎片 / 细胞",
	"reward_harvest": "大量金币 / 细胞",
	"reward_hack": "底层源代码",
	"reward_boss": "区块推进",

	# ---------------- 房间异常规则 ----------------
	"mod_heat_surge": "高热",
	"mod_heat_surge_desc": "过载增长 ×1.5",
	"mod_chill": "冷流场",
	"mod_chill_desc": "泄压效率 +60%",
	"mod_shielded": "自带护盾",
	"mod_shielded_desc": "所有敌人带护盾",
	"mod_swarm": "蜂群",
	"mod_swarm_desc": "敌人数量 +50%，血量 -25%",
	"mod_armored": "重装甲",
	"mod_armored_desc": "敌人血量 +60%，数量 -25%",
	"mod_fog": "浓雾",
	"mod_fog_desc": "视野受限",
	"mod_blackout": "停电",
	"mod_blackout_desc": "画面变暗，敌人伤害 -20%",
	"mod_surge": "电涌池",
	"mod_surge_desc": "地面出现周期放电区",
	"mod_coolant": "冷却池",
	"mod_coolant_desc": "站上去快速降温但减速",
	"mod_reflect": "反射镜",
	"mod_reflect_desc": "子弹会反射 1 次",
	"mod_gravity": "重力错乱",
	"mod_gravity_desc": "敌人更快，玩家略慢",
	"mod_overclocked": "超频区",
	"mod_overclocked_desc": "敌人更快，金币 +35%",

	# ---------------- 标签 ----------------
	"tag_OVERCLOCK": "过载",
	"tag_CRYO": "冰结",
	"tag_ARC": "电弧",
	"tag_VOID": "虚空",
	"tag_SALVAGE": "拾荒",
	"tag_FORTIFY": "要塞",
	"tag_PRECISION": "精密",
	"tag_oc_2": "过载 ≥70% 时伤害 +10%",
	"tag_oc_4": "过载 ≥70% 时伤害 +22%",
	"tag_oc_6": "过载 ≥70% 时伤害 +38%",
	"tag_cryo_2": "冻结时长 +0.5s",
	"tag_cryo_4": "冻结目标额外承受 +25% 伤害",
	"tag_cryo_6": "冻结目标死亡时爆裂",
	"tag_arc_2": "电弧弹射 +1 次",
	"tag_arc_4": "弹射伤害衰减降低",
	"tag_arc_6": "命中 8% 概率再触发一次电弧",
	"tag_void_2": "HP<40% 时伤害 +12%",
	"tag_void_4": "HP<40% 时移速 +12%",
	"tag_void_6": "HP<40% 时暴击 +25%",
	"tag_sal_2": "金币获取 +20%",
	"tag_sal_4": "金币与细胞 +20%",
	"tag_sal_6": "掉落品质提高",
	"tag_fort_2": "受到伤害 -8%",
	"tag_fort_4": "治疗瓶 +1",
	"tag_fort_6": "致命伤免疫一次（每局一次）",
	"tag_prec_2": "暴击率 +8%",
	"tag_prec_4": "暴击伤害 2.0 → 2.5 倍",
	"tag_prec_6": "暴击重置翻滚冷却",
	"fortify_last_stand": "要塞协议：核心强制重启！",

	# ---------------- 卷轴 ----------------
	"scroll_title": "过载卷轴 —— 选择一项强化",
	"scroll_firepower": "火力",
	"scroll_firepower_desc": "全武器伤害 +15%",
	"scroll_cooling": "散热",
	"scroll_cooling_desc": "射速提升 · 冷却 ×0.88",
	"scroll_structure": "结构",
	"scroll_structure_desc": "最大 HP +15 并回复 15",
	"scroll_energy": "能量",
	"scroll_energy_desc": "能量碎片 +30",

	# ---------------- 协议 ----------------
	"proto_siphon": "汲能协议",
	"proto_siphon_desc": "每次击杀回复 %d HP",
	"proto_phase": "相位协议",
	"proto_phase_desc": "翻滚后 2 秒伤害 +%d%%",
	"proto_magnet": "磁场协议",
	"proto_magnet_desc": "掉落吸取范围 +%d",
	"proto_overclock": "超频协议",
	"proto_overclock_desc": "暴击率 +%d%%",
	"proto_armor": "装甲协议",
	"proto_armor_desc": "受到伤害 -%d%%",
	"proto_capacitor": "电容协议",
	"proto_capacitor_desc": "治疗瓶充能 +%d",
	"proto_chain": "链式反应协议",
	"proto_chain_desc": "击杀时 %d%% 概率引爆",
	"proto_execution": "处决协议",
	"proto_execution_desc": "HP 低于 %d%% 的敌人承受双倍伤害",
	"proto_vent": "泄压阀协议",
	"proto_vent_desc": "泄压效率 +%d%%",
	"proto_vampiric": "汲血协议",
	"proto_vampiric_desc": "暴击回复 %d HP",
	"proto_cryo_field": "冷冻场协议",
	"proto_cryo_field_desc": "命中附带 %d%% 冻结概率",
	"proto_salvage_rig": "拾荒装置协议",
	"proto_salvage_rig_desc": "金币与细胞 +%d%%",
	"proto_gained": "已装备协议",
	"proto_upgraded": "协议升级",

	# ---------------- 武器 ----------------
	"w_pulse": "脉冲发生器",
	"w_scatter": "散射矩阵",
	"w_railgun": "轨道穿刺",
	"w_homing": "蜂群导弹",
	"w_orbiter": "哨戒无人机",
	"w_arc": "电弧切割器",
	"w_cryo": "液氮喷口",
	"w_nova": "星爆核心",
	"w_mortar": "熔解迫击炮",
	"w_drill": "相位钻头",
	"w_leech": "汲能束",
	"w_mirror": "镜像棱镜",
	"weapon_gained": "获得武器",
	"weapon_swap": "切换武器",

	# ---------------- 过载卡 ----------------
	"card_allin": "全核超频",
	"card_allin_desc": "伤害 +60%、射速 +20%，但过载增长 ×2",
	"card_ice": "冰封协议",
	"card_ice_desc": "命中 20% 概率冻结，冻结目标死亡爆裂",
	"card_repair": "自动修复",
	"card_repair_desc": "每 8 杀回复 5 HP，但金币 -25%",
	"card_mirror": "镜像火力",
	"card_mirror_desc": "全弹道 +1，但伤害 -20%",
	"card_hack": "黑客模式",
	"card_hack_desc": "商店 -40%，但必出 1 件诅咒货",
	"card_reload": "重载",
	"card_reload_desc": "翻滚后下一击必暴击，但翻滚 CD +50%",
	"card_fission": "裂变",
	"card_fission_desc": "伤害 +35%，但最大 HP -15%",
	"card_salvage": "拾荒狂潮",
	"card_salvage_desc": "金币 +80%、细胞 +50%，但伤害 -15%",

	# ---------------- 商店 / 宝箱 ----------------
	"shop_hint": "按 E 购买（靠近货架）",
	"shop_buy_weapon": "随机武器",
	"shop_buy_heal": "应急维修 +40 HP",
	"shop_buy_scroll": "过载卷轴",
	"shop_buy_protocol": "协议模块",
	"shop_buy_card": "过载卡",
	"shop_buy_energy": "能量碎片 ×40",
	"shop_bought": "购买成功",
	"shop_poor": "金币不足",
	"shop_discount": "黑客模式折扣",
	"chest_hint": "按 E 开启诅咒宝箱（会引来敌人）",
	"chest_opened": "宝箱开启 —— 过载反噬！",
	"chest_reward": "获得卷轴 + 30 金币",

	# ---------------- 交互提示（走近可交互物时 HUD 弹出的「[E] 做什么」）----------------
	"prompt_chest": "开启诅咒宝箱",
	"prompt_shop": "花费 %d 金币购买",
	"prompt_hack": "接入骇入终端",
	"prompt_repair": "修复供电节点 %d / %d",
	"prompt_key": "E",

	# ---------------- 侧边指导栏（可折叠）----------------
	"guide_title": "操 作 指 南",
	"guide_toggle": "收起 / 展开",
	"guide_collapsed_hint": "操作指南（按 Tab 展开）",
	"guide_move": "移动：WASD / 方向键",
	"guide_shoot": "射击：自动朝鼠标方向开火",
	"guide_roll": "翻滚：空格（有无敌帧）",
	"guide_swap": "换武器：Q",
	"guide_skill": "技能：右键 / Shift",
	"guide_flask": "应急修复：F",
	"guide_interact": "交互：走近目标按 E",
	"guide_shop": "商店：靠近货架按 E 花金币购买",
	"guide_chest": "宝箱：靠近按 E 开启（会引来敌人）",
	"guide_hack": "骇入终端：靠近按 E 进入打飞机小游戏",
	"guide_glitch": "故障节点：记住闪烁顺序，走近按 E 依次修复",
	"guide_overload": "过载：越高收益越高，满格会崩溃刷出故障体",
	"guide_vent": "泄压：按住泄压键降低过载",
	"guide_lang": "切换语言：L",

	# ---------------- 开场漫画引导 ----------------
	"intro_page": "第 %d / %d 页",
	"intro_hint": "→ / 空格 下一页　← 上一页　Esc 跳过",
	"intro_menu_btn": "剧情引导",
	"intro_menu_sub": "重温 4 页开场漫画",

	# ---------------- 房间机制文案 ----------------
	"repair_title": "维修完成",
	"repair_done": "核心维修：+%d HP，过载 -%d",
	"lab_title": "实验室 —— 选择一次实验规则",
	"lab_hint": "实验结果会立刻作用于本局构筑",
	"glitch_title": "故障房 —— 按顺序修复供电节点",
	"glitch_hint": "记住闪烁顺序，走近后按 E 依次修复",
	"glitch_progress": "节点 %d / %d",
	"glitch_success": "管线已接通！",
	"glitch_fail": "顺序错误 —— 重新开始",
	"glitch_timeout": "超时 —— 故障扩散",
	"harvest_title": "收割房 —— 限时击杀挑战",
	"harvest_hint": "在 %d 秒内击杀尽可能多的敌人",
	"harvest_progress": "剩余 %d 秒 · 已击杀 %d",
	"harvest_success": "收割完成：奖励结算",
	"harvest_fail": "收割结束",
	"elite_room_hint": "精英出没 —— 高价值掉落",
	"energy_gain": "能量碎片 +%d",

	# ---------------- 底层骇入 ----------------
	"hack_title": "底层骇入",
	"hack_subtitle": "KERNEL HACK // 数据包渗透",
	"hack_start": "开始骇入",
	"hack_hint": "WASD / 鼠标移动 · 自动开火 · 击穿防火墙",
	"hack_wave": "第 %d 波 / %d",
	"hack_boss": "防火墙 已激活",
	"hack_clear": "骇入成功 —— 取出底层源代码",
	"hack_fail": "连接中断 —— 仅取回部分数据",
	"hack_reward": "底层源代码 +%d",
	"hack_score": "骇入得分 %d",
	"hack_exit": "按 E 退出",
	"hack_shield": "数据护盾",
	"skill_overclock_pulse": "系统技能：超频脉冲",
	"skill_cryo_nova": "系统技能：冰冻新星",
	"skill_arc_storm": "系统技能：电弧风暴",
	"skill_phase_dash": "系统技能：相位冲刺",
	"skill_magnet_sweep": "系统技能：磁力掠夺",
	"skill_force_field": "系统技能：力场护盾",
	"skill_weak_scan": "系统技能：弱点扫描",
	"skill_emergency_stop": "系统技能：急停降温",
	"skill_ready": "技能就绪",

	# ---------------- 路线图 ----------------
	"route_title": "系统拓扑图 —— 选择下一个节点",
	"route_hint": "当前可选节点已高亮；点击选择，或按 1/2/3 键",
	"route_risk": "风险",
	"route_reward": "奖励",
	"route_depth": "第 %d 层",
	"route_boss": "区块 BOSS",
	"route_biome": "区块 %d",
	"route_cleared": "已通过",

	# ---------------- 奖励三选一 ----------------
	"reward_title": "选择一项奖励",
	"reward_reroll": "重掷（剩余 %d）",
	"reward_reroll_none": "无重掷次数",
	"reward_scope_scroll": "卷轴",
	"reward_scope_weapon": "武器",
	"reward_scope_protocol": "协议",
	"reward_scope_card": "过载卡",
	"card_rooms": "持续 %d 个房间",
	"picked_prefix": "拾取",

	# ---------------- 暂停 ----------------
	"pause_title": "系统挂起",
	"pause_resume": "继续",
	"pause_save_quit": "保存并退出",
	"pause_build": "查看构筑",
	"pause_abandon": "放弃本局",
	"pause_saved": "已保存到断点",
	"pause_save_hint": "断点仅在安全状态写入",
	"pause_abandon_confirm": "确认放弃？存档将被删除",
	"pause_abandon_yes": "确认放弃",
	"pause_abandon_no": "取消",

	# ---------------- 结算 ----------------
	"game_over_title": "核心过载",
	"game_over_stats": "击杀 %d · 深度 %d · 得分 %d",
	"game_over_cells": "细胞兑换：%d 科技点",
	"game_over_source": "取得底层源代码：%d",
	"victory_title": "主脑已回收",
	"victory_stats": "通关！击杀 %d · 得分 %d",
	"victory_source": "通关奖励：底层源代码 +%d",
	"restart_hint": "按 R 重新开始 · ESC 返回主菜单",
	"chain_reward": "连锁 %d —— 额外金币",
	"biome_source_gain": "区块清除：底层源代码 +%d",
	"boss_incoming": "警告 —— %s 已上线",

	# ---------------- 主菜单 ----------------
	"menu_start": "新的一局",
	"menu_start_sub": "以全新状态进入地牢，杀回主脑",
	"menu_continue": "继续 Run",
	"menu_continue_sub": "区块 %d · 深度 %d · HP %d/%d",
	"menu_continue_none": "没有可用的断点存档",
	"menu_collector": "收集者",
	"menu_collector_sub": "科技点 %d · 源代码 %d",
	"menu_archive": "收藏者档案",
	"menu_archive_sub": "武器 %d/%d · 协议 %d/%d · 过载卡 %d/%d",
	"menu_language": "语言和设置",
	"menu_language_sub": "界面语言 · 音效音量 · 画面选项",
	"menu_quit": "退出",
	"menu_quit_sub": "离开游戏",
	"menu_hint": "战斗中按 ESC 打开暂停菜单（可保存断点）",
	"menu_status_online": "核心状态 在线",

	# ---------------- 收集者 ----------------
	"collector_title": "收集者 —— 局外成长",
	"collector_tech": "科技点：%d",
	"collector_source": "底层源代码：%d",
	"collector_buy": "购买",
	"collector_max": "已满级",
	"collector_poor": "资源不足",
	"collector_branch_numeric": "数值强化（科技点）",
	"collector_branch_unlock": "玩法解锁（底层源代码）",

	"meta_armor": "核心装甲",
	"meta_armor_desc": "初始 HP +8 / 级",
	"meta_phase": "相位引擎",
	"meta_phase_desc": "翻滚冷却 -12% / 级",
	"meta_funds": "启动资金",
	"meta_funds_desc": "开局金币 +25 / 级",
	"meta_serum": "应急血清",
	"meta_serum_desc": "治疗瓶充能 +1 / 级",
	"meta_power": "能源工程",
	"meta_power_desc": "过载抗性 +8%、泄压 +25% / 级",
	"meta_lab": "武器实验室",
	"meta_lab_desc": "逐级解锁 3–12 号武器池",
	"meta_research": "协议研究",
	"meta_research_desc": "逐级解锁高级协议",
	"meta_hack": "骇入强化",
	"meta_hack_desc": "骇入奖励 +20%、初始护盾 +1 / 级",
	"meta_reroll": "折叠协议",
	"meta_reroll_desc": "每区块奖励重掷 +1 次 / 级",
	"meta_challenge": "挑战协议",
	"meta_challenge_desc": "解锁挑战词缀系统",

	# ---------------- 图鉴 ----------------
	"archive_title": "收藏者档案 —— 图鉴",
	"archive_weapons": "武器",
	"archive_protocols": "协议",
	"archive_cards": "过载卡",
	"archive_bosses": "Boss",
	"archive_events": "事件",
	"archive_unknown": "未发现",
	"archive_progress": "已收录 %d / %d",
	"archive_hint": "在 Run 中遇到即自动收录",

	# ---------------- 挑战词缀 ----------------
	"challenge_title": "挑战词缀 —— 开局前自由组合",
	"challenge_locked": "需要通过「收集者 · 挑战协议」解锁",
	"challenge_thermal": "热能失控",
	"challenge_thermal_desc": "过载积累 +35%",
	"challenge_noheal": "无治疗",
	"challenge_noheal_desc": "所有治疗效果减半",
	"challenge_glass": "玻璃核心",
	"challenge_glass_desc": "最大 HP -30%",
	"challenge_signal": "双重信号",
	"challenge_signal_desc": "远程敌人数量 +50%",
	"challenge_blackout": "全面停电",
	"challenge_blackout_desc": "部分房间持续停电，掉落品质 +1",
	"challenge_hunger": "饥饿",
	"challenge_hunger_desc": "房间清空奖励减少，Boss 细胞 +50%",
	"challenge_none": "未选择任何词缀",

	# ---------------- 设置 ----------------
	"settings_title": "语言和设置",
	"settings_language": "界面语言",
	"settings_volume": "音效音量",
	"settings_crt": "CRT 滤镜",
	"settings_shake": "屏幕抖动",
	"settings_colorblind": "高对比危险提示",
	"lang_zh": "中文",
	"lang_en": "English",
	"back": "返回",
	"close": "关闭",
	"on": "开",
	"off": "关",
}


const _EN := {
	"game_title": "Dungeon Overlord: Overload Crisis",
	"game_title_en": "CORE OVERLOAD",
	"version_tag": "V1.3",
	"tutorial_t1": "WASD move · Mouse aim · LMB fire · Q swap weapon",
	"tutorial_t2": "Shift / Space: dodge roll (i-frames)",
	"tutorial_t3": "Hold V: manual vent (cannot shoot while venting)",
	"tutorial_t4": "F: flask · R: build skill · Tab: build · ESC: pause / save",
	"tutorial_t5": "After a clear, pick the next node on the route map; checkpoints auto-save in safe states",
	"lang_switch_hint": "Press L to switch language",

	"room_tutorial": "TRAINING SIM",
	"reward_tutorial": "Master every control",
	"tutorial_title": "CONTROL TRAINING",
	"tutorial_hud_tag": "TRAINING MODE",
	"tutorial_step_label": "TRAINING %d / %d",
	"tutorial_goal_move": "Move with W A S D to the glowing marker",
	"tutorial_goal_shoot": "Aim at the dummy with the mouse, hold LMB to fire · land 3 hits",
	"tutorial_goal_roll": "Press Shift or Space to dodge roll · rolls grant i-frames",
	"tutorial_goal_swap": "Press Q to swap weapons (a secondary weapon has been issued)",
	"tutorial_goal_vent": "Hold V to vent and push OVERLOAD below 5% (you cannot fire while venting)",
	"tutorial_goal_skill": "Press R to fire your system skill · it depends on your build",
	"tutorial_done": "Training complete · step onto the exit gate on the right",
	"tutorial_dummy": "TRAINING DUMMY",
	"tutorial_move_marker": "STEP HERE",
	"tutorial_swap_bonus": "TRAINING SUPPLY: secondary weapon issued",
	"tutorial_hint_safe": "No damage in the training sim · ESC pauses and lets you abandon",
	"menu_tutorial": "Training Level",
	"menu_tutorial_sub": "Replay the control tutorial · does not touch your save",

	"hud_hp": "HP",
	"hud_gold": "GOLD",
	"hud_cells": "CELLS",
	"hud_energy": "ENERGY",
	"hud_source": "SOURCE",
	"hud_kills": "KILLS",
	"hud_score": "SCORE",
	"hud_room": "ROOM",
	"hud_flask": "FLASK",
	"hud_fire": "FIRE",
	"hud_cool": "COOL",
	"hud_struct": "STRUCT",
	"hud_weapon": "WPN",
	"hud_empty": "EMPTY",
	"hud_roll": "ROLL",
	"hud_overload": "OVERLOAD",
	"hud_build": "BUILD",
	"hud_chain": "CHAIN",
	"hud_depth": "DEPTH",
	"hud_rules": "ANOMALY",
	"hud_no_rule": "NONE",

	"overload_stable": "STABLE",
	"overload_high": "HIGH LOAD",
	"overload_danger": "DANGER",
	"overload_critical": "CRITICAL",
	"overload_meltdown": "MELTDOWN",
	"overload_vent_hint": "Hold V to vent",
	"overload_vented": "VENTING",
	"melt_blackout": "BLACKOUT - all systems down",
	"melt_surge": "SURGE - glitch entities inbound",
	"melt_burn": "CORE SCORCH - HP lost",
	"melt_emp": "EMP PULSE - overload purged, resources refunded",

	"biome_1": "Coolant Channels",
	"biome_2": "Server Graveyard",
	"biome_3": "The Core Mind",
	"room_combat": "COMBAT",
	"room_elite": "ELITE",
	"room_treasure": "TREASURE",
	"room_repair": "REPAIR",
	"room_shop": "BLACK MARKET",
	"room_lab": "LAB",
	"room_glitch": "GLITCH",
	"room_harvest": "HARVEST",
	"room_hack": "KERNEL HACK",
	"room_boss": "BOSS",
	"room_clear": "ROOM CLEARED",
	"room_locked": "WARNING: doors locked",
	"room_next": "Pick the next node on the route map",

	"reward_combat": "Gold / cells",
	"reward_elite": "High-grade scroll / protocol",
	"reward_treasure": "Chest / scroll",
	"reward_repair": "Heal / purge overload",
	"reward_shop": "Gold trading",
	"reward_lab": "Temporary augment",
	"reward_glitch": "Energy / cells",
	"reward_harvest": "Massive gold / cells",
	"reward_hack": "Source code",
	"reward_boss": "Biome progress",

	"mod_heat_surge": "HEAT SURGE",
	"mod_heat_surge_desc": "Overload gain x1.5",
	"mod_chill": "CHILL FIELD",
	"mod_chill_desc": "Vent efficiency +60%",
	"mod_shielded": "SHIELDED",
	"mod_shielded_desc": "All enemies carry shields",
	"mod_swarm": "SWARM",
	"mod_swarm_desc": "Enemy count +50%, HP -25%",
	"mod_armored": "ARMORED",
	"mod_armored_desc": "Enemy HP +60%, count -25%",
	"mod_fog": "FOG",
	"mod_fog_desc": "Limited vision",
	"mod_blackout": "BLACKOUT",
	"mod_blackout_desc": "Screen dims, enemy damage -20%",
	"mod_surge": "SURGE POOL",
	"mod_surge_desc": "Pools discharge on a timer",
	"mod_coolant": "COOLANT POOL",
	"mod_coolant_desc": "Stand on it to cool fast, but slower",
	"mod_reflect": "MIRRORS",
	"mod_reflect_desc": "Bullets bounce once",
	"mod_gravity": "GRAVITY FAULT",
	"mod_gravity_desc": "Enemies faster, player slower",
	"mod_overclocked": "OVERCLOCKED",
	"mod_overclocked_desc": "Faster enemies, gold +35%",

	"tag_OVERCLOCK": "OVERCLOCK",
	"tag_CRYO": "CRYO",
	"tag_ARC": "ARC",
	"tag_VOID": "VOID",
	"tag_SALVAGE": "SALVAGE",
	"tag_FORTIFY": "FORTIFY",
	"tag_PRECISION": "PRECISION",
	"tag_oc_2": "+10% damage while overload >= 70%",
	"tag_oc_4": "+22% damage while overload >= 70%",
	"tag_oc_6": "+38% damage while overload >= 70%",
	"tag_cryo_2": "Freeze duration +0.5s",
	"tag_cryo_4": "Frozen targets take +25% damage",
	"tag_cryo_6": "Frozen kills explode",
	"tag_arc_2": "+1 arc chain",
	"tag_arc_4": "Lower chain falloff",
	"tag_arc_6": "8% chance to re-trigger arc",
	"tag_void_2": "+12% damage below 40% HP",
	"tag_void_4": "+12% move speed below 40% HP",
	"tag_void_6": "+25% crit below 40% HP",
	"tag_sal_2": "+20% gold",
	"tag_sal_4": "+20% gold and cells",
	"tag_sal_6": "Better drop quality",
	"tag_fort_2": "-8% damage taken",
	"tag_fort_4": "+1 flask charge",
	"tag_fort_6": "Immune to one lethal hit per run",
	"tag_prec_2": "+8% crit chance",
	"tag_prec_4": "Crit damage 2.0 -> 2.5x",
	"tag_prec_6": "Crit resets roll cooldown",
	"fortify_last_stand": "FORTIFY: core force-restarted!",

	"scroll_title": "OVERLOAD SCROLL - choose one",
	"scroll_firepower": "FIREPOWER",
	"scroll_firepower_desc": "All weapon damage +15%",
	"scroll_cooling": "COOLING",
	"scroll_cooling_desc": "Fire rate up - cooldown x0.88",
	"scroll_structure": "STRUCTURE",
	"scroll_structure_desc": "Max HP +15 and heal 15",
	"scroll_energy": "ENERGY",
	"scroll_energy_desc": "Energy fragments +30",

	"proto_siphon": "Siphon Protocol",
	"proto_siphon_desc": "Heal %d HP per kill",
	"proto_phase": "Phase Protocol",
	"proto_phase_desc": "+%d%% damage for 2s after rolling",
	"proto_magnet": "Magnet Protocol",
	"proto_magnet_desc": "Pickup radius +%d",
	"proto_overclock": "Overclock Protocol",
	"proto_overclock_desc": "Crit chance +%d%%",
	"proto_armor": "Armor Protocol",
	"proto_armor_desc": "Damage taken -%d%%",
	"proto_capacitor": "Capacitor Protocol",
	"proto_capacitor_desc": "Flask charge +%d",
	"proto_chain": "Chain Reaction",
	"proto_chain_desc": "%d%% chance to detonate on kill",
	"proto_execution": "Execution",
	"proto_execution_desc": "Double damage below %d%% HP",
	"proto_vent": "Relief Valve",
	"proto_vent_desc": "Vent efficiency +%d%%",
	"proto_vampiric": "Vampiric",
	"proto_vampiric_desc": "Crits heal %d HP",
	"proto_cryo_field": "Cryo Field",
	"proto_cryo_field_desc": "%d%% freeze chance on hit",
	"proto_salvage_rig": "Salvage Rig",
	"proto_salvage_rig_desc": "Gold and cells +%d%%",
	"proto_gained": "Protocol equipped",
	"proto_upgraded": "Protocol upgraded",

	"w_pulse": "PULSE",
	"w_scatter": "SCATTER",
	"w_railgun": "RAILGUN",
	"w_homing": "SWARM",
	"w_orbiter": "SENTRY",
	"w_arc": "ARC CUTTER",
	"w_cryo": "CRYO NOZZLE",
	"w_nova": "NOVA CORE",
	"w_mortar": "MELT MORTAR",
	"w_drill": "PHASE DRILL",
	"w_leech": "LEECH BEAM",
	"w_mirror": "MIRROR PRISM",
	"weapon_gained": "Weapon acquired",
	"weapon_swap": "Weapon swapped",

	"card_allin": "ALL-IN",
	"card_allin_desc": "+60% damage, +20% rate, overload gain x2",
	"card_ice": "ICE PROTOCOL",
	"card_ice_desc": "20% freeze on hit; frozen kills burst",
	"card_repair": "AUTO REPAIR",
	"card_repair_desc": "Heal 5 every 8 kills, gold -25%",
	"card_mirror": "MIRROR FIRE",
	"card_mirror_desc": "+1 projectile, damage -20%",
	"card_hack": "HACK MODE",
	"card_hack_desc": "Shop -40%, one cursed item guaranteed",
	"card_reload": "RELOAD",
	"card_reload_desc": "Next shot after roll crits, roll CD +50%",
	"card_fission": "FISSION",
	"card_fission_desc": "+35% damage, max HP -15%",
	"card_salvage": "SALVAGE RUSH",
	"card_salvage_desc": "Gold +80%, cells +50%, damage -15%",

	"shop_hint": "Press E to buy (stand near a shelf)",
	"shop_buy_weapon": "Random weapon",
	"shop_buy_heal": "Repair +40 HP",
	"shop_buy_scroll": "Overload scroll",
	"shop_buy_protocol": "Protocol module",
	"shop_buy_card": "Overclock card",
	"shop_buy_energy": "Energy fragments x40",
	"shop_bought": "Purchased",
	"shop_poor": "Not enough gold",
	"shop_discount": "Hack mode discount",
	"chest_hint": "Press E to open the cursed chest",
	"chest_opened": "Chest opened - OVERLOAD BACKLASH!",
	"chest_reward": "Scroll + 30 gold",

	# ---------------- interaction prompts ----------------
	"prompt_chest": "Open cursed chest",
	"prompt_shop": "Buy for %d gold",
	"prompt_hack": "Jack into terminal",
	"prompt_repair": "Repair power node %d / %d",
	"prompt_key": "E",

	# ---------------- collapsible guide panel ----------------
	"guide_title": "C O N T R O L S",
	"guide_toggle": "collapse / expand",
	"guide_collapsed_hint": "Guide (press Tab to expand)",
	"guide_move": "Move: WASD / arrows",
	"guide_shoot": "Fire: auto-fire toward cursor",
	"guide_roll": "Roll: Space (has i-frames)",
	"guide_swap": "Swap weapon: Q",
	"guide_skill": "Skill: RMB / Shift",
	"guide_flask": "Emergency repair: F",
	"guide_interact": "Interact: walk up and press E",
	"guide_shop": "Shop: press E at a rack to spend gold",
	"guide_chest": "Chest: press E nearby (draws enemies)",
	"guide_hack": "Terminal: press E to enter the shooter mini-game",
	"guide_glitch": "Glitch nodes: memorize the blink order, press E in sequence",
	"guide_overload": "Overload: higher = better rewards, full = crash spawns glitches",
	"guide_vent": "Vent: hold the vent key to lower overload",
	"guide_lang": "Switch language: L",

	# ---------------- opening comic ----------------
	"intro_page": "Page %d / %d",
	"intro_hint": "-> / Space next   <- back   Esc skip",
	"intro_menu_btn": "Story Intro",
	"intro_menu_sub": "Replay the 4-page comic",

	"repair_title": "REPAIRED",
	"repair_done": "Core serviced: +%d HP, overload -%d",
	"lab_title": "LAB - choose one experiment",
	"lab_hint": "The result immediately changes your build",
	"glitch_title": "GLITCH - repair power nodes in order",
	"glitch_hint": "Memorise the flash order, walk up and press E",
	"glitch_progress": "Nodes %d / %d",
	"glitch_success": "Circuit restored!",
	"glitch_fail": "Wrong order - restarting",
	"glitch_timeout": "Timed out - fault spreading",
	"harvest_title": "HARVEST - timed kill challenge",
	"harvest_hint": "Kill as many as you can in %d seconds",
	"harvest_progress": "%d s left - %d kills",
	"harvest_success": "Harvest complete",
	"harvest_fail": "Harvest ended",
	"elite_room_hint": "Elite present - high value drops",
	"energy_gain": "Energy +%d",

	"hack_title": "KERNEL HACK",
	"hack_subtitle": "KERNEL HACK // packet infiltration",
	"hack_start": "BEGIN",
	"hack_hint": "WASD / mouse to move - auto fire - break the firewall",
	"hack_wave": "WAVE %d / %d",
	"hack_boss": "FIREWALL online",
	"hack_clear": "HACK COMPLETE - source code extracted",
	"hack_fail": "CONNECTION LOST - partial data recovered",
	"hack_reward": "Source code +%d",
	"hack_score": "Hack score %d",
	"hack_exit": "Press E to exit",
	"hack_shield": "DATA SHIELD",
	"skill_overclock_pulse": "Skill: Overclock Pulse",
	"skill_cryo_nova": "Skill: Cryo Nova",
	"skill_arc_storm": "Skill: Arc Storm",
	"skill_phase_dash": "Skill: Phase Dash",
	"skill_magnet_sweep": "Skill: Magnet Sweep",
	"skill_force_field": "Skill: Force Field",
	"skill_weak_scan": "Skill: Weak Scan",
	"skill_emergency_stop": "Skill: Emergency Stop",
	"skill_ready": "Skill ready",

	"route_title": "SYSTEM TOPOLOGY - choose your next node",
	"route_hint": "Highlighted nodes are available; click or press 1/2/3",
	"route_risk": "RISK",
	"route_reward": "REWARD",
	"route_depth": "Layer %d",
	"route_boss": "BIOME BOSS",
	"route_biome": "BIOME %d",
	"route_cleared": "cleared",

	"reward_title": "CHOOSE A REWARD",
	"reward_reroll": "Reroll (%d left)",
	"reward_reroll_none": "No rerolls",
	"reward_scope_scroll": "SCROLL",
	"reward_scope_weapon": "WEAPON",
	"reward_scope_protocol": "PROTOCOL",
	"reward_scope_card": "CARD",
	"card_rooms": "Lasts %d rooms",
	"picked_prefix": "Picked up",

	"pause_title": "SYSTEM SUSPENDED",
	"pause_resume": "RESUME",
	"pause_save_quit": "SAVE & QUIT",
	"pause_build": "VIEW BUILD",
	"pause_abandon": "ABANDON RUN",
	"pause_saved": "Checkpoint saved",
	"pause_save_hint": "Checkpoints are only written in safe states",
	"pause_abandon_confirm": "Abandon? The checkpoint will be deleted.",
	"pause_abandon_yes": "CONFIRM",
	"pause_abandon_no": "CANCEL",

	"game_over_title": "CORE OVERLOAD",
	"game_over_stats": "Kills %d · Depth %d · Score %d",
	"game_over_cells": "Cells converted: %d tech points",
	"game_over_source": "Source code recovered: %d",
	"victory_title": "CORE RECLAIMED",
	"victory_stats": "Victory! Kills %d · Score %d",
	"victory_source": "Victory bonus: source code +%d",
	"restart_hint": "Press R to restart · ESC for menu",
	"chain_reward": "CHAIN %d - bonus gold",
	"biome_source_gain": "Biome cleared: source code +%d",
	"boss_incoming": "WARNING - %s is online",

	"menu_start": "NEW RUN",
	"menu_start_sub": "Begin a fresh run, fight back to the core",
	"menu_continue": "CONTINUE RUN",
	"menu_continue_sub": "Biome %d · depth %d · HP %d/%d",
	"menu_continue_none": "No checkpoint available",
	"menu_collector": "THE COLLECTOR",
	"menu_collector_sub": "Tech %d · Source %d",
	"menu_archive": "ARCHIVE",
	"menu_archive_sub": "Weapons %d/%d · Protocols %d/%d · Cards %d/%d",
	"menu_language": "LANGUAGE & SETTINGS",
	"menu_language_sub": "Language · Volume · Display",
	"menu_quit": "QUIT",
	"menu_quit_sub": "Exit game",
	"menu_hint": "Press ESC in a run for the pause menu (save checkpoint)",
	"menu_status_online": "CORE STATUS ONLINE",

	"collector_title": "THE COLLECTOR - meta progression",
	"collector_tech": "Tech points: %d",
	"collector_source": "Source code: %d",
	"collector_buy": "BUY",
	"collector_max": "MAXED",
	"collector_poor": "Not enough",
	"collector_branch_numeric": "NUMERIC (tech points)",
	"collector_branch_unlock": "UNLOCKS (source code)",
	"hud_tags": "TAGS",
	"hud_cards": "CARDS",
	"hud_scrolls": "SCROLLS",

	"meta_armor": "Core Armor",
	"meta_armor_desc": "Starting HP +8 / level",
	"meta_phase": "Phase Engine",
	"meta_phase_desc": "Roll cooldown -12% / level",
	"meta_funds": "Startup Funds",
	"meta_funds_desc": "Starting gold +25 / level",
	"meta_serum": "Emergency Serum",
	"meta_serum_desc": "+1 flask charge / level",
	"meta_power": "Power Engineering",
	"meta_power_desc": "+8% overload resist, +25% vent / level",
	"meta_lab": "Weapon Lab",
	"meta_lab_desc": "Unlocks weapons 3-12 progressively",
	"meta_research": "Protocol Research",
	"meta_research_desc": "Unlocks advanced protocols",
	"meta_hack": "Hack Rig",
	"meta_hack_desc": "+20% hack reward, +1 starting shield / level",
	"meta_reroll": "Fold Protocol",
	"meta_reroll_desc": "+1 reward reroll per biome / level",
	"meta_challenge": "Challenge Protocol",
	"meta_challenge_desc": "Unlocks the challenge modifier system",

	"archive_title": "ARCHIVE",
	"archive_weapons": "WEAPONS",
	"archive_protocols": "PROTOCOLS",
	"archive_cards": "CARDS",
	"archive_bosses": "BOSSES",
	"archive_events": "EVENTS",
	"archive_unknown": "UNDISCOVERED",
	"archive_progress": "%d / %d collected",
	"archive_hint": "Anything you meet in a run is recorded here",

	"challenge_title": "CHALLENGE MODIFIERS",
	"challenge_locked": "Unlock via Collector > Challenge Protocol",
	"challenge_thermal": "THERMAL RUN",
	"challenge_thermal_desc": "Overload gain +35%",
	"challenge_noheal": "NO HEAL",
	"challenge_noheal_desc": "All healing halved",
	"challenge_glass": "GLASS CORE",
	"challenge_glass_desc": "Max HP -30%",
	"challenge_signal": "DOUBLE SIGNAL",
	"challenge_signal_desc": "Ranged enemies +50%",
	"challenge_blackout": "BLACKOUT",
	"challenge_blackout_desc": "Some rooms stay dark, drop tier +1",
	"challenge_hunger": "HUNGER",
	"challenge_hunger_desc": "Lower room rewards, boss cells +50%",
	"challenge_none": "No modifiers selected",

	"settings_title": "LANGUAGE & SETTINGS",
	"settings_language": "Interface Language",
	"settings_volume": "Sound Volume",
	"settings_crt": "CRT Filter",
	"settings_shake": "Screen Shake",
	"settings_colorblind": "High-contrast danger cues",
	"lang_zh": "中文",
	"lang_en": "English",
	"back": "Back",
	"close": "Close",
	"on": "ON",
	"off": "OFF",
}


func _ready() -> void:
	_load()
	lang_zh = (lang == "zh")


func is_zh() -> bool:
	return lang_zh


func apply(new_lang: String) -> void:
	if new_lang != "zh" and new_lang != "en":
		return
	if new_lang == lang:
		return
	lang = new_lang
	lang_zh = (lang == "zh")
	_save()
	language_changed.emit(lang)


func t(key: String) -> String:
	var d: Dictionary = _ZH if lang_zh else _EN
	var v: Variant = d.get(key, null)
	if v == null:
		v = _EN.get(key, key)
	return str(v)


func has(key: String) -> bool:
	if _ZH.has(key):
		return true
	return _EN.has(key)


func f(key: String, args: Array) -> String:
	var fmt: String = t(key)
	if args.is_empty():
		return fmt
	return fmt % args


func toggle() -> void:
	apply("en" if lang_zh else "zh")


func _load() -> void:
	if not FileAccess.file_exists(FILE_PATH):
		return
	var f := FileAccess.open(FILE_PATH, FileAccess.READ)
	if f == null:
		return
	var parsed: Variant = JSON.parse_string(f.get_as_text())
	if parsed is Dictionary and (parsed as Dictionary).has("lang"):
		lang = "zh" if (parsed as Dictionary)["lang"] == "zh" else "en"


func _save() -> void:
	var f := FileAccess.open(FILE_PATH, FileAccess.WRITE)
	if f == null:
		return
	f.store_string(JSON.stringify({"lang": lang}))
